name: Lint and Format
on:
  pull_request:
    branches:
      - master
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Check and fix linting issues
        run: npm run lint:fix
      - name: Check and fix formatting issues
        run: npm run format:fix
      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: lint and format check fixes"
            git fetch origin
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          fi
