name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  playwright:
    name: 'Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shard }}'
    env:
      SYS_ADMIN_USERNAME: ${{ secrets.SYS_ADMIN_USERNAME }}
      SYS_ADMIN_PASSWORD: ${{ secrets.SYS_ADMIN_PASSWORD }}
      SYS_ADMIN_FULLNAME: ${{ secrets.SYS_ADMIN_FULLNAME }}
      INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.0-jammy
    strategy:
      fail-fast: false
      matrix:
        project: [chrome, safari, android, iOS]
        shard: [1/10, 2/10, 3/10, 4/10, 5/10, 6/10, 7/10, 8/10, 9/10, 10/10]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shard }}
      - name: Rename blob-report directory
        run: mv blob-report ${{ matrix.project }}-blob-report
      - name: Rename blob-reports
        run: for f in ${{ matrix.project }}-blob-report/*; do mv "$f" "${{ matrix.project }}-$f"; done
      - name: Upload blob report'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: all-blob-reports
          path: blob-report-${{ matrix.project }}
          retention-days: 1
  merge-reports:
    if: always()
    needs: [playwright]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Download blob reports
        uses: actions/download-artifact@v3
        with:
          name: all-blob-reports
          path: all-blob-reports
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
