name: Playwright Tests
on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     type: choice
    #     description: 'Environment to run tests against'
    #     options:
    #       - ALPHA
    #       - BETA
    #       - QA
    #       - IST
    #       - VPRIOR
    #       - VNEXT
    #       - PROD
    #     required: true
    #     default: ALPHA
jobs:
  generate_shards:
    name: 'Generate Shards'
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.generate_shards.outputs.shards }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate shards
        id: generate_shards
        run: |
          #!/bin/bash
          test_directory="tests"

          test_count=0

          while IFS= read -r file; do
            count=$(grep -c "test(" "$file")
            test_count=$((test_count + count))
          done < <(find "$test_directory" -type f -name '*.spec.ts')

          min_shards=10
          max_tests_per_shard=20

          num_of_shards=$((test_count / max_tests_per_shard))

          if [ "$num_of_shards" -eq 0 ]; then
            num_of_shards=min_shards
          fi

          shards_array=()

          for i in {1..10}; do
            shards_array+=("$i/$num_of_shards")
          done

          # Output the result and the array
          echo "Total test calls: $total_count"
          echo "Total shards: $num_of_shards"
          echo "shards=$num_of_shards" >> $GITHUB_OUTPUT
  run_tests:
    name: 'Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shard }}'
    needs: generate_shards
    env:
      CI: true
      SYS_ADMIN_USERNAME: ${{ secrets.SYS_ADMIN_USERNAME }}
      SYS_ADMIN_PASSWORD: ${{ secrets.SYS_ADMIN_PASSWORD }}
      SYS_ADMIN_FIRST_NAME: ${{ secrets.SYS_ADMIN_FIRST_NAME }}
      SYS_ADMIN_LAST_NAME: ${{ secrets.SYS_ADMIN_LAST_NAME }}
      SYS_ADMIN_EMAIL: ${{ secrets.SYS_ADMIN_EMAIL }}
      TEST_ENV: ${{ github.event.inputs.environment }}
      ALPHA_INSTANCE_URL: ${{ secrets.ALPHA_INSTANCE_URL }}
      BETA_INSTANCE_URL: ${{ secrets.BETA_INSTANCE_URL }}
      QA_INSTANCE_URL: ${{ secrets.QA_INSTANCE_URL }}
      IST_INSTANCE_URL: ${{ secrets.IST_INSTANCE_URL }}
      VPRIOR_INSTANCE_URL: ${{ secrets.VPRIOR_INSTANCE_URL }}
      VNEXT_INSTANCE_URL: ${{ secrets.VNEXT_INSTANCE_URL }}
      PROD_INSTANCE_URL: ${{ secrets.PROD_INSTANCE_URL }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    strategy:
      fail-fast: false
      matrix:
        project: [chrome, edge]
        shard: [1/10, 2/10, 3/10, 4/10, 5/10, 6/10, 7/10, 8/10, 9/10, 10/10]
    steps:
      - name: Echo shards
        run: echo ${{ needs.generate_shards.outputs.shards }}
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest
      # - name: Install dependencies
      #   run: npm ci
      # - name: Run your tests
      #   run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shard }}
